### PR TITLE
-n flag and compiler warning fixes

### PR DESCRIPTION
**Pull request by ghost**
I have added the "-o" option to select only one file with Enter / ".".
I have also fixed the compiler warnings and disabled warnings about set but not used variables.

### CODE REVIEW

**Review by ihaveadrin — CHANGES_REQUESTED** [review]
The type changes are sound, I need to test them.
But first!
A flag is better than my approach of the dot key, i prefer that, but why an entire new function for your mode? It isn't a library, you could add an arg to fs_curs_sel or use a global variable and an if into the "case KEY_ENTER" part.

**Comment by ihaveadrin** [comment]
Also, for the -c flag in README that I hadn't documented because I thought it was useless, put there a bracketed (default) and we're set. Thanks!

**Comment by dyveloper** [comment]
That may be a better idea. Would you also prefer a command line option to specify an exact amount of files to be selected or do you want to keep only the -o option?Am 03.02.2019 18:19 schrieb Teodoro Santoni <notifications@github.com>:@ihaveadrin requested changes on this pull request.

The type changes are sound, I need to test them.
But first!
A flag is better than my approach of the dot key, i prefer that, but why an entire new function for your mode? It isn't a library, you could add an arg to fs_curs_sel or use a global variable and an if into the "case KEY_ENTER" part.

**Comment by ghost** [comment]
@ihaveadrin That may be a better idea. Would you also prefer a command line option to specify an exact amount of files to be selected or do you want to keep only the -o option?

**Comment by ihaveadrin** [comment]
@dyveloper the original fselect aimed to select an indefinite quantity of files. I think that for cases like, e.g. a wrapper for selecting a file and then a destination directory where to copy it, I'd leave the enforcement of selecting only two elements to the script that would wrap `fselect`. With a limitation on selected files probably you would need to give in argv a whole region of the filesystem or its entirety.

Thanks!

**Comment by ghost** [comment]
@ihaveadrin I have replaced -o with -n now to specify a max. amount of selections. -n 1 does the same as -o. I have also put both in one function and -n works also in -y mode. A selection limit is disabled by default.

**Comment by ihaveadrin** [comment]
Done. Thanks for your work.

**Comment by ghost** [comment]
@ihaveadrin you're welcome

**Pull request merged**
